name: Run Dog Assignment Script

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  optimize:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install gspread oauth2client requests
    
    - name: Create credentials.json
      env:
        CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
      run: |
        echo "$CREDENTIALS" > credentials.json
        ls -la credentials.json  # Verify file was created
    
    - name: Run optimization
      run: python production_reassignment.py
    
    - name: Clean up
      if: always()
      run: rm -f credentials.json
